### ISSUE TITLE
error when prepare own model

### ISSUE THREAD

**Issue by yuxin212** [HendrikStrobelt/Seq2Seq-Vis#22]
Hi,

When I used your modified opennmt to prepare my model, I called like this:

python extract_context.py -src s2s/src-train.txt -tgt s2s/tgt-train.txt -model s2s/demo-5.pt -batch_size 64

And I got this error:

Traceback (most recent call last):
  File "extract_context.py", line 356, in <module>
    main()
  File "extract_context.py", line 335, in main
    onmt.ModelConstructor.load_test_model(opt, dummy_opt.__dict__)
  File "/home/cc/OpenNMT-py/onmt/ModelConstructor.py", line 119, in load_test_model
    map_location=lambda storage, loc: storage)
  File "/home/cc/miniconda2/envs/s2sv/lib/python3.6/site-packages/torch/serialization.py", line 358, in load
    return _load(f, map_location, pickle_module)
  File "/home/cc/miniconda2/envs/s2sv/lib/python3.6/site-packages/torch/serialization.py", line 542, in _load
    result = unpickler.load()
ModuleNotFoundError: No module named 'onmt.utils'

I trained my model using OpenNMT-py without your modification. 

Thank you.

**Comment by msalameh83** [comment]
I am also getting the same error

**Comment by sebastianGehrmann** [comment]
That looks like there is an incopatibility with some ONMT version and our extraction. Could you give me more information? What commit did you use to train the model?

**Comment by sebastianGehrmann** [comment]
OpenNMT underwent a significant refactor this summer which breaks backwards compatibility in some cases. I am currently working on updating the server to work with newer versions. Until then, you can use commits around this one `3bd519070ad3b092dc081d2e72d0cd129bd085c7`.

**Comment by yuxin212** [comment]
> OpenNMT underwent a significant refactor this summer which breaks backwards compatibility in some cases. I am currently working on updating the server to work with newer versions. Until then, you can use commits around this one `3bd519070ad3b092dc081d2e72d0cd129bd085c7`.

Thank you so much!
